clear; clc; close all;

%% SELECT ROOT FOLDER
rootDir = uigetdir(pwd, 'Select ROOT folder containing participant folders');

if isequal(rootDir, 0)
    error('No root folder selected.');
end

%% OUTPUT LOG FOLDER
batchLogFolder = fullfile(rootDir, 'ORIENTATION_Batch_Logs');

if ~exist(batchLogFolder, 'dir')
    mkdir(batchLogFolder);
end

%% FIND PARTICIPANT FOLDERS
participants = dir(fullfile(rootDir, 'P*'));
participants = participants([participants.isdir]);

fprintf('\nParticipants found:\n');
disp({participants.name}');

%% INITIALIZE LOG
OrientationLog = table();

%% LOOP THROUGH PARTICIPANTS
for p = 1:length(participants)

    participantID = string(participants(p).name);
    participantPath = fullfile(rootDir, participants(p).name);

    fprintf('\n=====================================\n');
    fprintf('PARTICIPANT %s\n', char(participantID));
    fprintf('=====================================\n');

    %% FIND TRIAL FOLDERS
    trialFolders = dir(participantPath);
    trialFolders = trialFolders([trialFolders.isdir]);
    trialFolders = trialFolders(~ismember({trialFolders.name}, {'.','..'}));

    trialNames = {trialFolders.name};

    % Keep folders like T1, T2, T3, T1W, T2W, T3W
    keepTrial = ~cellfun(@isempty, regexp(trialNames, '^T\d+W?$', 'once', 'ignorecase'));
    trialFolders = trialFolders(keepTrial);

    for tr = 1:length(trialFolders)

        trialFolderName = string(trialFolders(tr).name);
        trialPath = fullfile(participantPath, trialFolders(tr).name);

        syncFolder = fullfile(trialPath, 'SYNC_Results_TimestampBased');
        syncMatFile = fullfile(syncFolder, 'Synchronized_IMU_Data.mat');

        fprintf('\nProcessing MagON orientation: %s | %s\n', ...
            char(participantID), char(trialFolderName));

        %% CHECK SYNC FILE EXISTS
        if ~isfile(syncMatFile)

            warning('No synchronized MAT file found. Skipping.');

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(trialPath), ...
                string(syncFolder), ...
                false, ...
                "Skipped: synchronized MAT file not found", ...
                NaN, ...
                NaN, ...
                NaN, ...
                NaN, ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'TrialPath', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'NumSegments', ...
                    'Duration_s', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            OrientationLog = [OrientationLog; newRow];
            continue;
        end

        %% RUN MAG ON ORIENTATION ESTIMATION
        try

            status = estimate_orientations_magON_one_trial_function(syncFolder);

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(trialPath), ...
                string(syncFolder), ...
                logical(status.Success), ...
                string(status.Message), ...
                double(status.NumSegments), ...
                double(status.Duration_s), ...
                double(status.StaticStart_s), ...
                double(status.StaticEnd_s), ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'TrialPath', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'NumSegments', ...
                    'Duration_s', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            OrientationLog = [OrientationLog; newRow];

            fprintf('SUCCESS: %s | %s\n', char(participantID), char(trialFolderName));

        catch ME

            warning('FAILED: %s | %s | %s', ...
                char(participantID), char(trialFolderName), ME.message);

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(trialPath), ...
                string(syncFolder), ...
                false, ...
                string(ME.message), ...
                NaN, ...
                NaN, ...
                NaN, ...
                NaN, ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'TrialPath', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'NumSegments', ...
                    'Duration_s', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            OrientationLog = [OrientationLog; newRow];

        end

    end
end

%% SAVE LOG
logFile = fullfile(batchLogFolder, 'Batch_Orientation_Log_MagON.csv');
writetable(OrientationLog, logFile);

fprintf('\n=====================================\n');
fprintf('BATCH MAGON ORIENTATION COMPLETE\n');
fprintf('=====================================\n');

fprintf('\nLog saved to:\n%s\n', logFile);

%% SUMMARY
nTotal = height(OrientationLog);
nSuccess = sum(OrientationLog.Success);
nFailed = nTotal - nSuccess;

fprintf('\nTrials attempted: %d\n', nTotal);
fprintf('Successful: %d\n', nSuccess);
fprintf('Failed/skipped: %d\n', nFailed);