clear; clc; close all;

%% SELECT ROOT FOLDER
rootDir = uigetdir(pwd, 'Select ROOT folder containing participant folders');

if isequal(rootDir, 0)
    error('No root folder selected.');
end

%% LOG FOLDER
logFolder = fullfile(rootDir, 'STATIC_STO_Batch_Logs');

if ~exist(logFolder, 'dir')
    mkdir(logFolder);
end

StaticLog = table();

%% FIND PARTICIPANTS
participants = dir(fullfile(rootDir, 'P*'));
participants = participants([participants.isdir]);

fprintf('\nParticipants found:\n');
disp({participants.name}');

%% LOOP THROUGH PARTICIPANTS
for p = 1:length(participants)

    participantID = string(participants(p).name);
    participantPath = fullfile(rootDir, participants(p).name);

    fprintf('\n=====================================\n');
    fprintf('PARTICIPANT %s\n', char(participantID));
    fprintf('=====================================\n');

    %% FIND TRIAL FOLDERS
    trialFolders = dir(participantPath);
    trialFolders = trialFolders([trialFolders.isdir]);
    trialFolders = trialFolders(~ismember({trialFolders.name}, {'.','..'}));

    trialNames = {trialFolders.name};

    % Keep T1, T2, T3, T1W, T2W, T3W
    keepTrial = ~cellfun(@isempty, regexp(trialNames, '^T\d+W?$', 'once', 'ignorecase'));
    trialFolders = trialFolders(keepTrial);

    for tr = 1:length(trialFolders)

        trialFolderName = string(trialFolders(tr).name);

        trialPath = fullfile(participantPath, trialFolders(tr).name);
        syncFolder = fullfile(trialPath, 'SYNC_Results_TimestampBased');
        syncMatFile = fullfile(syncFolder, 'Synchronized_IMU_Data.mat');

        orientationFolder = fullfile(syncFolder, 'Orientation_Results_MagOFF');
        staticSTO = fullfile(orientationFolder, 'OpenSim_Orientations_Static_MagOFF.sto');

        fprintf('\nCreating static STO: %s | %s\n', ...
            char(participantID), char(trialFolderName));

        %% CHECK SYNC FILE
        if ~isfile(syncMatFile)

            warning('Synchronized_IMU_Data.mat not found. Skipping.');

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(syncFolder), ...
                false, ...
                "Skipped: synchronized MAT file not found", ...
                NaN, ...
                NaN, ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            StaticLog = [StaticLog; newRow];
            continue;
        end

        %% RUN STATIC EXPORT
        try

            result = export_static_calibration_sto_one_trial_function(syncFolder);

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(syncFolder), ...
                true, ...
                "Static calibration STO exported successfully", ...
                result.StaticStart_s, ...
                result.StaticEnd_s, ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            StaticLog = [StaticLog; newRow];

            fprintf('SUCCESS: %s | %s\n', char(participantID), char(trialFolderName));

        catch ME

            warning('FAILED: %s | %s | %s', ...
                char(participantID), char(trialFolderName), ME.message);

            newRow = table( ...
                participantID, ...
                trialFolderName, ...
                string(syncFolder), ...
                false, ...
                string(ME.message), ...
                NaN, ...
                NaN, ...
                'VariableNames', { ...
                    'Participant', ...
                    'TrialFolder', ...
                    'SyncFolder', ...
                    'Success', ...
                    'Message', ...
                    'StaticStart_s', ...
                    'StaticEnd_s'});

            StaticLog = [StaticLog; newRow];

        end
    end
end

%% SAVE LOG
logFile = fullfile(logFolder, 'Batch_Static_STO_Export_Log.csv');
writetable(StaticLog, logFile);

fprintf('\n=====================================\n');
fprintf('BATCH STATIC STO EXPORT COMPLETE\n');
fprintf('=====================================\n');

fprintf('\nLog saved to:\n%s\n', logFile);

fprintf('\nTrials attempted: %d\n', height(StaticLog));
fprintf('Successful static exports: %d\n', sum(StaticLog.Success));
fprintf('Failed/skipped: %d\n', height(StaticLog) - sum(StaticLog.Success));