function QC_Row = qc_single_INDIP_sensor(filename, plotFolder)

%% SETTINGS
fs_expected = 100;
dt_expected_ms = 1000/fs_expected;

acc_limit_g = 8;
gyro_limit_dps = 2000;
mag_limit_mGauss = 50000;

static_search_seconds = 6;
static_window_seconds = 2;

[~, fileBase, ext] = fileparts(filename);
filename = string([fileBase ext]);

fprintf('Processing sensor file: %s\n', filename);

%% READ DEVICE ID FROM HEADER
fileText = fileread(filename);
deviceMatch = regexp(fileText, 'Id:\s*(INDIP#d+)', 'tokens');

if isempty(deviceMatch)
    deviceID = "UnknownDevice";
else
    deviceID = string(deviceMatch{1}{1});
end

%% READ DATA TABLE
opts = detectImportOptions(filename, ...
    'FileType','text', ...
    'Delimeter', '\t');

opts.VariableNamesLine = 19;
opts.DataLines = [21 Inf];

T = readtable(filename, opts);
T.properties.VariableNames = matlab.lang.makeValidName(T.Properties.VariableNames);

%% EXTRACT SIGNALS
timestamp = T.Timestamp;
t = (timestamp - timestamp(1))/1000;

ax = T.Acc_X /1000;
ay = T.Acc_Y /1000;
az = T.Acc_Z /1000;

gx = T.Gyro_X;
gy = T.Gyro_Y;
gz = T.Gyro_Z;

mx = T.Magn_X;
my = T.Magn_Y;
mz = T.Magn_Z;

%% TIMESTAMP
dt = diff(timestamp);

nSamples = height(T);
duration_timestamp = (timestamp(end) - timestamp(1))/1000;
duration_sample_based = (nSamples -1)/fs_expected;

TimestampVsSampleDrif_s = duration_timestamp - duration_sample_based;

dropped_packets = sum(dt > 1.5*dt_expected_ms);
duplicate_timestamps = sum(dt == 0);
negative_time_jumps = sum(dt < 0);

clean_dt = dt(dt > 0 & dt < 1.5*dt_expected_ms);

mean_dt = mean(dt);
std_dt = std(dt);
min_dt = min(dt);
max_dt = max(dt);

clean_mean_dt = mean(clean_dt);
clean_std_dt = std(clean_dt);
clean_rate_Hz = 1000 / clean_mean_dt;

%% MAGNITUDES
acc_mag = sqrt(ax.^2 + ay.^2 + az.^2);
gyro_mag = sqrt(gx.^2 + gy.^2 + gz.^2);
mag_mag = sqrt(mx.^2 + my.^2 + mz.^2);

%% SATURATION CHECKS
acc_saturation = sum(abs(ax) > 0.98*acc_limit_g | ...
    abs(ay) > 0.98*acc_limit_g | ...
    abs(az) > 0.98*acc_limit_g);

gyro_saturation = sum(abs(gx) > 0.98*gyro_limit_dps | ...
                      abs(gy) > 0.98*gyro_limit_dps | ...
                      abs(gz) > 0.98*gyro_limit_dps);

mag_saturation = sum(abs(mx) > 0.98*mag_limit_mGauss | ...
                     abs(my) > 0.98*mag_limit_mGauss | ...
                     abs(mz) > 0.98*mag_limit_mGauss);

%% AUTOMATIC STATIC WINDOW DETECTION
window_samples = round(static_window_seconds * fs_expected);
searchidx = find(t <= static_search_seconds);

scores = nan(length(search_idx), 1);

if length(searchidx) > window_samples

    for k = 1:(length(searchidx)-window_samples)

        idx = search_idx(k):(search_idx(k)+window_samples-1)
        acc_mag_mean = mean(acc_mag(idx));
        acc_mag_std = std(acc_mag(idx));
        gyro_mag_mean = mean(gyro_mag(idx));

        scores(k) = abs(acc_mag_mean - 1) + acc_mag_std + 0.01*gyro_mag_mean;

    end

        [~, best_k] = min(scores);

    static_start_idx = search_idx(best_k);
    static_end_idx = static_start_idx + window_samples - 1;

else

    warning('File too short for static-window detection. Using first available samples.');
    static_start_idx = 1;
    static_end_idx = min(length(t), window_samples);

end

static_idx = false(size(t));
static_idx(static_start_idx:static_end_idx) = true;

%% STATIC METRICS
mean_ax_static = mean(ax(static_idx));
mean_ay_static = mean(ay(static_idx));
mean_az_static = mean(az(static_idx));

static_acc_vector = [mean_ax_static, mean_ay_static, mean_az_static];

[~, dominant_axis_index] = max(abs(static_acc_vector));

axis_names = ["X","Y","Z"];
dominant_gravity_axis = axis_names(dominant_axis_index);
dominant_gravity_value = static_acc_vector(dominant_axis_index);

if dominant_gravity_value >= 0
    gravity_axis_sign = "+";
else
    gravity_axis_sign = "-";
end

gravity_axis_label = gravity_axis_sign + dominant_gravity_axis;

gyro_bias_x = mean(gx(static_idx));
gyro_bias_y = mean(gy(static_idx));
gyro_bias_z = mean(gz(static_idx));

gyro_noise_x = std(gx(static_idx));
gyro_noise_y = std(gy(static_idx));
gyro_noise_z = std(gz(static_idx));

static_acc_mag_mean = mean(acc_mag(static_idx));
static_acc_mag_std = std(acc_mag(static_idx));

static_mag_mag_mean = mean(mag_mag(static_idx));
static_mag_mag_std = std(mag_mag(static_idx));

%% SAVE QC ROW
QC_Row = table( ...
    fileName, ...
    deviceID, ...
    nSamples, ...
    timestamp(1), ...
    timestamp(end), ...
    duration_timestamp, ...
    duration_sample_based, ...
    TimestampVsSamplesDrift_s, ...
    mean_dt, std_dt, min_dt, max_dt, ...
    clean_mean_dt, clean_std_dt, clean_rate_Hz, ...
    dropped_packets, duplicate_timestamps, negative_time_jumps, ...
    acc_saturation, gyro_saturation, mag_saturation, ...
    min(acc_mag), max(acc_mag), ...
    min(gyro_mag), max(gyro_mag), ...
    min(mag_mag), max(mag_mag), ...
    static_start_time, static_end_time, ...
    mean_ax_static, mean_ay_static, mean_az_static, ...
    string(gravity_axis_label), ...
    gyro_bias_x, gyro_bias_y, gyro_bias_z, ...
    gyro_noise_x, gyro_noise_y, gyro_noise_z, ...
    static_acc_mag_mean, static_acc_mag_std, ...
    static_mag_mag_mean, static_mag_mag_std);

QC_Row.Properties.VariableNames = { ...
    'File', ...
    'DeviceID', ...
    'Samples', ...
    'StartTimestamp_ms', ...
    'EndTimestamp_ms', ...
    'Duration_Timestamp_s', ...
    'Duration_SampleBased_s', ...
    'TimestampVsSamplesDrift_s', ...
    'Mean_dt_ms', ...
    'Std_dt_ms', ...
    'Min_dt_ms', ...
    'Max_dt_ms', ...
    'CleanMean_dt_ms', ...
    'CleanStd_dt_ms', ...
    'CleanRate_Hz', ...
    'DroppedPackets', ...
    'DuplicateTimestamps', ...
    'NegativeTimeJumps', ...
    'AccSaturationSamples', ...
    'GyroSaturationSamples', ...
    'MagSaturationSamples', ...
    'AccMag_Min_g', ...
    'AccMag_Max_g', ...
    'GyroMag_Min_dps', ...
    'GyroMag_Max_dps', ...
    'MagMag_Min_mGauss', ...
    'MagMag_Max_mGauss', ...
    'StaticStartTime_s', ...
    'StaticEndTime_s', ...
    'StaticMeanAccX_g', ...
    'StaticMeanAccY_g', ...
    'StaticMeanAccZ_g', ...
    'DominantGravityAxis', ...
    'GyroBias_X_dps', ...
    'GyroBias_Y_dps', ...
    'GyroBias_Z_dps', ...
    'GyroNoise_X_dps', ...
    'GyroNoise_Y_dps', ...
    'GyroNoise_Z_dps', ...
    'StaticAccMag_Mean_g', ...
    'StaticAccMag_STD_g', ...
    'StaticMagMag_Mean_mGauss', ...
    'StaticMagMag_STD_mGauss'};

%% PLOTS
save_sensor_qc_plots( ...
    fileName, plotFolder, ...
    t, dt, ...
    ax, ay, az, ...
    gx, gy, gz, ...
    mx, my, mz, ...
    acc_mag, gyro_mag, mag_mag, ...
    static_start_time, static_end_time, ...
    dt_expected_ms);

end